### ISSUE TITLE
Get back format setting information

### ISSUE THREAD

**Issue by NicoHood** [jmcnamara/excel-writer-xlsx#151]
Hi,
I have a has of different formats for different things. Each "thing" has a different color. Since I need to create a whole new format for each "thing" I saved the whole format in the hash. If a new "thing" of a different sort appears I create the new format and add it with a new color.

Afterwards I want to create a legend of those colors. Meaning I need to get back the color. Since I saved the whole format, not just the color name, I cannot get back the name.

I could have saved the color name, but then I need to create a format for every "thing", even with the same type/color. I could also just access the "private" variables of the format object (havent tried that yet). Maybe you could provide some "getters" instead of only "setters" for those format functions as well?

Example:
```
set_color()
get_color()
```

**Comment by jmcnamara** [comment]
Hi,

In general I'm against storing and returning user data since Perl already has a rich set of tools to do that and a user doesn't need help from Excel::Writer::XLSX to do it.

I prefer to concentrate on functionality the user can't provide themselves. So this is a "Won't fix".

You can peer behind the OO curtain if you like and see what values are stored in the object. However, it probably isn't the value you added. For example:

```perl
#!/usr/bin/perl

use strict;
use warnings;

use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'demo.xlsx' );
my $worksheet = $workbook->add_worksheet();

my $format1 = $workbook->add_format( color => 'blue' );
my $format2 = $workbook->add_format( color => '#aabbcc' );

print $format1->{_color}, "\n";
print $format2->{_color}, "\n";

$workbook->close();
__END__

Prints:
    12
    #aabbcc
``` 

Note, if you are trying to identify duplicate formats in your application there is an undocumented Format method that might help you called `get_format_key()` that will return a unique identifier for the object:

```perl
print $format1->get_format_key(), "\n";
print $format2->get_format_key(), "\n";
```

It can be used as a key into a hash. That is how the module avoids storing duplicate formats.
