### ISSUE TITLE
How to remove the Â from the file.

### ISSUE THREAD

**Issue by Hari3288** [jmcnamara/excel-writer-xlsx#159]
Hi,

We have process in our system to convert the XLSX file to CSV format using perl script, During that process when we check for the CSV file we found that special character (Â) is getting populated in csv value which is causing the issue in further process, Could you please help us how to remove this special character during csv file generation.

Thanks in advance.

**Comment by jmcnamara** [comment]
Hi,

This isn't an Excel::Writer::XLSX issue so you shouldn't open an issue tracker. It would probably be better to ask this on stackoverflow.

Anyway, rather than remove special characters you should determine the encoding that they are in and read them in that encoding to ensure that they get converted to UTF-8. After that Excel::Writer::XLSX will handle them automatically. See the unicode examples in the Excel::Writer::XLSX starting here: http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX/Examples.pm#Example:_unicode_2022_jp.pl

You just need to figure out the encoding of the file you are trying to read and how to read it correctly with the CSV module that you are using.

John.
--
