### ISSUE TITLE
Embedded newlines

### ISSUE THREAD

**Issue by Tux** [jmcnamara/excel-writer-xlsx#163]
If I have a value that contains embedded newlines, and I write that like
``` perl
    $fmt{wrap} = $wbk->add_format (text_wrap => 1);
:
    if ($utf) {
        from_to ($val, "utf-8", "ucs2");
        $val =~ m/\n/
            ? $wks->write_unicode ($h, $c, $val, $fmt{wrap})
            : $wks->write_unicode ($h, $c, $val);
        }
    else {
        $val =~ m/\n/
            ? $wks->write_string  ($h, $c, $val, $fmt{wrap})
            : $wks->write_string  ($h, $c, $val);
    	}
```
All shows up rather fine. If the embedded newlines however are written on Windows, and stored as \r\n, the data shows as
```
foo_x000D_
bar
```
In this case it is easy to change that to
``` perl
    $val =~ s/\r\n/\n/g;
    if ($utf) {
        from_to ($val, "utf-8", "ucs2");
...
```
but I wonder is this behavior is the desired behavior.

**Comment by jmcnamara** [comment]
Hi Tux,

Long time no hear. There are a few, different, things in this issue.

1. A small complete working example would be better.
2. There is no `write_unicode()` method in Excel::Writer::XLSX. There was one in Spreadsheet::WriteExcel but even that has been deprecated since 2007. Again a small working example would clear that up.
3. In Excel::Writer::XLSX you don't need to distinguish between writing utf8 and non-utf8.
4. If you write "foo\r\nbar" with Excel::Writer::XLSX `write_string()` then you will, correctly, get "foo_x000D_\nbar" in the output file. That is the same behaviour as Excel.
5. If you write "foo\nbar" it isn't translated by`write_string()` to "\r\n".
6. You probably shouldn't have "\r" in your string data unless you read the input in some raw, or other, mode.
7. If `$val =~ s/\r\n/\n/g;` solves your problem then just use that. :-)

Regards,

John.

**Comment by Tux** [comment]
1. https://github.com/Tux/Text-CSV_XS/blob/master/examples/csv2xlsx
2. Removed in 1. I will remove write_unicode in https://github.com/Tux/Text-CSV_XS/blob/master/examples/csv2xls
3. noted (see 2)
4. Weird. when I opened the .xls in LibreOffice I did not see the _x000D_'s. I *did* see them in .xlsx
5. No surprise. I didn't state that.
6. Working with 3rd party data, I have no control over what I get. I agree
7. That is what it has now

**Comment by jmcnamara** [comment]
So, can I close the issue?

**Comment by Tux** [comment]
sure :)
