### ISSUE TITLE
Documentation omits two set_properties() fields

### ISSUE THREAD

**Issue by tsibley** [jmcnamara/excel-writer-xlsx#167]
The property fields `created` and `last_author` are supported by `$workbook->set_properties` but are not documented.

I [prepared a patch](https://github.com/jmcnamara/excel-writer-xlsx/pull/166/commits/46187f2d11fba01d6245057901e8cdd397980495) which adds them to the documentation out of a sense of completeness.  You may not agree that completeness is reason alone to be documented!  :-)

I have no use for `last_author`, but I do have a use for `created`.  Setting `created` lets me control what timestamp is written into the `docProps/core.xml` document.  When running the same script multiple times with the same spreadsheet contents, the timestamps in that file are the only bytes that change in the XML documents that make up the XLSX.  By being able to statically set the timestamp, I can ensure that the XML documents only change if the worksheets, cell contents, or formatting changes.  Without setting the timestamp, every new run produces a slightly different set of XML documents solely due to the timestamp reflecting "now".

**Comment by jmcnamara** [comment]
Hi Thomas,

> The property fields `created` and `last_author` are supported by `$workbook->set_properties` but are not documented.

This is intentional rather than an oversight.

> You may not agree that completeness is reason alone to be documented!

As it happens I don't. :-) I try not to give an emphasis to features that aren't important. When people ask for features I try to add them or to adjust the documentation to clarify usage.

Also, `created` and `last_author` aren't available in the Excel UI whereas the documented properties are.

So, since you don't need `last_author` and nobody else has asked for it I won't add that.

A couple of people (literally) have asked about the `created` property so that may be worth adding.

I'll address the second part of your question in #168.

John
