### ISSUE TITLE
Can't Locate Excel/Writer/XLSX.pm in @INC error is getting displayed.

### ISSUE THREAD

**Issue by Hari3288** [jmcnamara/excel-writer-xlsx#177]
Hi John,

While creating the Excel file through perl script i am getting the error "Can't Locate Excel/Writer/XLSX.pm in @INC error is getting displayed", But when i verified, the XLSX.pm is present in the required path, Could you please help me on this issue.

Thanks in advance.

**Comment by jmcnamara** [comment]
Hi,

That is a standard perl error that means that the module isn't installed or on a path available to perl.

I know you say that you verified that it is on the path but perl clearly thinks otherwise.

You can verify if the module is installed/available by running the following test program from the repo: https://github.com/jmcnamara/excel-writer-xlsx/blob/master/examples/bug_report.pl

John
