### ISSUE TITLE
Feature Request: Sunburst Chart Type

### ISSUE THREAD

**Issue by mlawren** [jmcnamara/excel-writer-xlsx#202]
I don't know when they were added, but Excel 2016 has a Sunburst chart type which it would be nice to be able to generate from Excel::Writer::XLSX. I had a quick look to see if I could fork one of the existing types into supporting sunbursts, but they appear at the XML level to be something rather different...

**Comment by jmcnamara** [comment]
Hi,

Sunburst charts were added in Excel 2016.

I don't have easy access to Excel 2016 at the moment so I don't know when I'll get to look at this. I'll leave the request open to gather some more +1s.

John

**Comment by jmcnamara** [comment]
I now have Excel 2016 and I looked into this chart types, and other new chart types such as Waterfall, Histogram, Pareto, Box and Whisker, Treemap, and Sunburst.

Unfortunately, these are structured completely differently from other, older, chart types and due to the amount of work involved these probably won't be added anything soon.

**Comment by mlawren** [comment]
No worries, thanks for looking.

-- 
Mark Lawrence
