### ISSUE TITLE
Issue: Using Excel::Writer::XLSX module to send an Excel file to a browser in a CGI program.

### ISSUE THREAD

**Issue by ViCLeon** [jmcnamara/excel-writer-xlsx#209]
Hi, 

I am having problems using the module to open an Excel file on the browser. I am testing the example called cgi.pl exactly as provided on the example list and getting this message when opening the .xlsx file. "Excel cannot open the file cgitest.xlsx because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file"

I'm working with module version 0.94.

![image](https://user-images.githubusercontent.com/38300079/38646249-ce3c25c4-3dac-11e8-8481-24acd491b172.png)

**Comment by jmcnamara** [comment]
Hi,

I don't have a CGI  environment and it has been about 10 years since I wrote or ran a CGI program.

If you are running the code exactly as it is in the example then the code itself should produce a valid Excel xlsx file.

I'd suggest asking a question on StackOverflow with the sample code you are using.

John
