### ISSUE TITLE
insert SVG images

### ISSUE THREAD

**Issue by kbrannen** [jmcnamara/excel-writer-xlsx#260]
It'd be really helpful if insert_image() could take SVG images and properly insert them. Probably have to use x_scale & y_scale for the desired size, or else add width & height options.

FWIW, I know Excel can take SVG or at least modern versions can, so the issue is the perl module.

I tried a quick hack on Workbook::_get_image_properties to see if I could make it work. I stopped the automatic rejection for bad type, but it failed overall as there were [obviously] other parts that needed change that I'm not aware of.

**Comment by jmcnamara** [comment]
I had a look at this recently for XlsxWriter here: https://github.com/jmcnamara/XlsxWriter/issues/608

I've copied the text below. It is written for Xlsxwriter the Python version of this library but it also applies to Excel::Writer::XLSX>


I've looked into this in a bit more detail and I don't think I can support SVG files in XlsxWriter. There are a number of technical issues that contribute to this:

- XlsxWriter needs to be able to determine the height, width and DPI for an image in order to position and scale it correctly in the appropriate Excel XML files. For SVG this seems hard. Particularly the DPI. However that isn't a blocker.
- SVG images weren't supported by Excel2007 so I can't generated sample files to use in test programs. This is more or less a blocker since image handling requires a lot of testing. (There are currently 107 tests that compare XlsxWriter output files containing images with Xlsx files generated in Excel).
- Excel versions that do support SVG do so by converting the image to a PNG and storing both the SVG and PNG in the xlsx file. This allows older versions of Excel to display the PNG. (Also, as far as I can see, the newer Excel versions that  support SVGs also display the PNG version, or at least reference the PNG version from the worksheet. They may just keep the SVG version around for export.) This is a blocker since XlsxWriter would have to convert the SVG to PNG and store both. This would need to happen via a third party module, which presumably is what user who needs to insert SVG images in XlsxWriter would do anyway.

So overall this is a can't fix/won't fix. Sorry.
