### ISSUE TITLE
Calculating of width of column inside _write_col_info()

### ISSUE THREAD

**Issue by milsorm** [jmcnamara/excel-writer-xlsx#271]
Hi John,

first of all - great module and many appricate for it. Really thanks a lot.

BUT I found some weird behaviour in `_write_col_info()`.

I pretty understand that sizes are stored as Calibri 11pt widths with implicit value of 8.43 (and for object/shapes/charts purposes you need to recalculate to pixels). BUT through `set_column()` we are setting widths in this Calibri-11pt values.

I don't understand why you recalculate `$width` inside that function when it is in Calibri-11pt values and need to produce Calibri-11pt values.

Even so that is not idemponent operation:

```
 $width =
              int( ( int( $width * $max_digit_width + 0.5 ) + $padding ) /
                  $max_digit_width *
                  256 ) / 256;
```

If `$max_digit_width` is 7 and `$padding` is 5, you can try with `$width` 8.43 that it produces 9.14 (because `$padding` is added and not subtracted later).

Why you are doing this? Are we able to prevent such operation?

I have templates prepared with `Spreadsheet::Template` created from original Excel XLSX (and converted to JSON format) and use the same module for creating XLSX with filled data and every single column is enlarged by 0.71mm due to this recalculation. So I am unable to create exact printable template.

Thanks for answer / solution / correction of such recalculation.

Best regards
Milan Sorm

**Comment by jmcnamara** [comment]
Hi Milan,

> I don't understand why you recalculate $width inside that function when it is in Calibri-11pt values and need to produce Calibri-11pt values.

The value stored in the Excel file isn't in Calibri-11pt values. At least not directly. For example if you set a column width of 12 units (89 pixels) in Excel the value will be stored as 12.7109375 in the file format. Hence, the calcuation.

> I have templates prepared with Spreadsheet::Template created from original Excel XLSX (and converted to JSON format) and use the same module for creating XLSX with filled data and every single column is enlarged by 0.71mm due to this recalculation. 

That sounds like it may be an issue with Spreadsheet::Template.

Either way I don't think that this is an issue with Excel::Writer::XLSX since it has over a 100 test cases that use `set_column()` and compare the output with files created by Excel to make sure they match exactly. Closing.
