### ISSUE TITLE
Merged cells next to each other

### ISSUE THREAD

**Issue by max-m-s** [jmcnamara/excel-writer-xlsx#90]
There is some strange behaviour when you write multiple merge_range cells next to each other.

This code will write four cells that are 1x2.

``` perl
#!/usr/bin/perl

use warnings;
use strict;
use Excel::Writer::XLSX;

my $fn = 'file.xlsx';
my $workbook = Excel::Writer::XLSX->new($fn);
my $worksheet = $workbook->add_worksheet();
my $vermerge = $workbook->add_format(
                            border  => 1,
                            valign  => 'top',
                            align   => 'left',
                            bold => 1,
                          );
my $x = 0;
foreach my $v ('col1','col2','col3','col4') {
    $worksheet->merge_range(0, $x, 1, $x, $v, $vermerge);
    $x++;
}
$workbook->close();
```

Only the first value is written out then the other three appear to have only been half formatted and have no value. See the screen shot.
![image](https://f.cloud.github.com/assets/6735507/2216812/906fed9a-9a11-11e3-8478-f483e5169907.png)

In my implementation, these would be followed a cell that spanned multiple columns in row 0, then individual cells in row 1. The cell that spanned multiple columns was also not written out correctly, but I have left that out to keep the example code simple.

P.S. This works normally using Spreadsheet::WriteExcel

**Comment by enerkeylog** [comment]
I have been faced a problem on merged cell and got a solution from this post. But now when I worked on excel work that time I got a popup notification on my screen [MS Excel Has Stopped Working Error](https://msofficetechnicalsupportnumbers.com/blog/how-to-fix-ms-excel-has-stopped-working-error/) and got a solution.

**Comment by jmcnamara** [comment]
@enerkeylog this issue is closed. 

If you have a new issue then please open a new GitHub issue with a small working program that demonstrates the issue. 

However, to save you some time, if you are having issues with merged ranges then it is usually due to having 2 (or more) merged ranges that are overlapping (which Excel doesn't allow and raised an error). Try debug your program and print out the ranges of any merged cells and look for any overlaps. If you still have an issue with a small complete working example.
